// Generated by dashboard/scripts/build-sample.mjs from dashboard/sample/sample-ledger.md. Do not edit by hand.
// This is made-up data for the "Try with sample data" button; nothing here comes from anyone's machine.
export default {
  "repo": "sample-project",
  "head": "a1b2c3d",
  "ledgerUpdatedAt": "2026-10-04T12:00:00.000Z",
  "generatedAt": "2026-10-04T12:00:00.000Z",
  "readOnly": true,
  "sample": true,
  "decisions": [
    {
      "id": "DEC-002",
      "kind": "decision",
      "status": "open",
      "from": "builder",
      "to": "human",
      "opened": "2026-10-04",
      "claimed": null,
      "closed": null,
      "section": "decisions",
      "title": "Should rate limits be per IP address or per API token?",
      "body": "Should rate limits be per IP address or per API token?\nPer-IP is simpler but unfair to people behind a shared network address. Per-token is fairer but needs the token store from TASK-003. I recommend per-token.",
      "review": null
    }
  ],
  "tasks": [
    {
      "id": "TASK-005",
      "kind": "task",
      "status": "open",
      "from": "architect",
      "to": "builder",
      "opened": "2026-10-04",
      "claimed": null,
      "closed": null,
      "section": "tasks",
      "title": "Implement the limiter in src/limiter.ts against the interface in src/types.ts.",
      "body": "Implement the limiter in src/limiter.ts against the interface in src/types.ts.\nAcceptance: `npm test` passes, including the burst test.",
      "review": null
    },
    {
      "id": "TASK-006",
      "kind": "task",
      "status": "open",
      "from": "architect",
      "to": "codex",
      "opened": "2026-10-04",
      "claimed": null,
      "closed": null,
      "section": "tasks",
      "title": "Write the migration that adds the rate_limits table.",
      "body": "Write the migration that adds the rate_limits table.\nAcceptance: it applies and rolls back cleanly on an empty database.",
      "review": null
    },
    {
      "id": "TASK-007",
      "kind": "task",
      "status": "open",
      "from": "reviewer",
      "to": "builder",
      "opened": "2026-10-04",
      "claimed": null,
      "closed": null,
      "section": "tasks",
      "title": "DEFECT in TASK-003: the token store only ignores expired tokens when reading, so expired tokens still count toward the limit.",
      "body": "DEFECT in TASK-003: the token store only ignores expired tokens when reading, so expired tokens still count toward the limit.\nReproduce: create a token, move the clock past its expiry, call limiter.check(); it should refuse but allows the request.",
      "review": "defect"
    }
  ],
  "done": [
    {
      "id": "TASK-004",
      "kind": "task",
      "status": "done",
      "from": "architect",
      "to": "codex",
      "opened": "2026-10-03",
      "claimed": null,
      "closed": "2026-10-04",
      "section": "done",
      "title": "Add a lint rule that bans console.log in src/.",
      "body": "Add a lint rule that bans console.log in src/.\nDone: added the rule to the lint config. `npm run lint` printed 0 problems. Not reviewed yet.",
      "review": null
    },
    {
      "id": "TASK-003",
      "kind": "task",
      "status": "done",
      "from": "architect",
      "to": "builder",
      "opened": "2026-10-03",
      "claimed": null,
      "closed": "2026-10-04",
      "section": "done",
      "title": "Add the token store in src/tokens.ts with create, lookup and expiry.",
      "body": "Add the token store in src/tokens.ts with create, lookup and expiry.\nDone: implemented it with 12 tests. `npm test` printed 12 passed, 0 failed. Not verified: behaviour under concurrent writes.\nDEFECT: the reviewer re-ran `npm test` (12 passed) but found a real bug in expiry handling and filed it as TASK-007.",
      "review": "defect"
    },
    {
      "id": "TASK-002",
      "kind": "task",
      "status": "done",
      "from": "architect",
      "to": "architect",
      "opened": "2026-10-03",
      "claimed": null,
      "closed": "2026-10-03",
      "section": "done",
      "title": "Define the limiter interface in src/types.ts: check(key), reset(key) and the config shape.",
      "body": "Define the limiter interface in src/types.ts: check(key), reset(key) and the config shape.\nDone: wrote the types and a short design note. Not verified: nothing runs yet, this is a contract only.\nPASS: the reviewer read the interface against the task and found it complete.",
      "review": "pass"
    },
    {
      "id": "DEC-001",
      "kind": "decision",
      "status": "done",
      "from": "builder",
      "to": "architect",
      "opened": "2026-10-03",
      "claimed": null,
      "closed": "2026-10-03",
      "section": "done",
      "title": "Should the token store use memory or Redis?",
      "body": "Should the token store use memory or Redis?\nAnswer: memory for now, behind an interface, so Redis can be added later.",
      "review": null
    }
  ],
  "checkpoints": [
    {
      "agent": "architect",
      "sha": "a1b2c3d",
      "stale": false
    },
    {
      "agent": "builder",
      "sha": "9f8e7d6",
      "stale": true
    },
    {
      "agent": "reviewer",
      "sha": "a1b2c3d",
      "stale": false
    },
    {
      "agent": "codex",
      "sha": "4c5d6e7",
      "stale": true
    }
  ],
  "counts": {
    "decisions": 1,
    "tasks": 3,
    "done": 4
  },
  "warnings": [],
  "attention": [
    {
      "level": "action",
      "text": "1 decision waiting for an answer. Work that depends on it is blocked.",
      "ids": [
        "DEC-002"
      ]
    },
    {
      "level": "action",
      "text": "1 defect filed by a reviewer and not yet fixed.",
      "ids": [
        "TASK-007"
      ]
    },
    {
      "level": "action",
      "text": "1 finished task has not been reviewed (done by codex). Start a reviewer session, or check the evidence yourself.",
      "ids": [
        "TASK-004"
      ]
    },
    {
      "level": "info",
      "text": "builder has 2 open tasks. Open builder in this repo and say \"pick up any work waiting for you\".",
      "ids": [
        "TASK-005",
        "TASK-007"
      ]
    },
    {
      "level": "info",
      "text": "codex has 1 open task. Open codex in this repo and say \"pick up any work waiting for you\".",
      "ids": [
        "TASK-006"
      ]
    }
  ]
};
