#!/usr/bin/env node
// Builds web/sample-state.js: the data behind the dashboard's "Try with sample data" button.
// It runs the REAL ledger parser over sample/sample-ledger.md, so the demo can never show a shape the
// server would not send. A test fails if the committed file is out of date.
//
//   node dashboard/scripts/build-sample.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { parseLedger } from "../server/parse-ledger.mjs";

const LEDGER = new URL("../sample/sample-ledger.md", import.meta.url);
const OUTPUT = new URL("../web/sample-state.js", import.meta.url);
const SAMPLE_HEAD = "a1b2c3d";
const SAMPLE_TIME = "2026-10-04T12:00:00.000Z";

export function buildSampleSource() {
  const parsed = parseLedger(readFileSync(LEDGER, "utf-8"), { head: SAMPLE_HEAD });
  const state = {
    repo: "sample-project",
    head: SAMPLE_HEAD,
    ledgerUpdatedAt: SAMPLE_TIME,
    generatedAt: SAMPLE_TIME,
    readOnly: true,
    sample: true,
    ...parsed,
  };
  return [
    "// Generated by dashboard/scripts/build-sample.mjs from dashboard/sample/sample-ledger.md. Do not edit by hand.",
    "// This is made-up data for the \"Try with sample data\" button; nothing here comes from anyone's machine.",
    `export default ${JSON.stringify(state, null, 2)};`,
    "",
  ].join("\n");
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeFileSync(OUTPUT, buildSampleSource());
  console.log("wrote dashboard/web/sample-state.js");
}
