import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { cpSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { buildSampleSource } from "../scripts/build-sample.mjs";

const here = (rel) => fileURLToPath(new URL(rel, import.meta.url));
const committed = () => readFileSync(here("../web/sample-state.js"), "utf-8");
const stateOf = (source) => JSON.parse(source.slice(source.indexOf("export default ") + "export default ".length).trim().replace(/;\s*$/, ""));

test("the committed sample data is exactly what the real parser makes of the sample ledger", () => {
  assert.equal(committed(), buildSampleSource(), "run: node dashboard/scripts/build-sample.mjs");
});

test("the sample ledger is a valid ledger by the kit's own validator", () => {
  const dir = mkdtempSync(path.join(tmpdir(), "sample-valid-"));
  try {
    const root = here("../../");
    assert.equal(spawnSync("bash", [path.join(root, "install.sh"), dir], { encoding: "utf-8" }).status, 0);
    cpSync(here("../sample/sample-ledger.md"), path.join(dir, ".ledger", "LEDGER.md"));
    const result = spawnSync("bash", [path.join(dir, ".ledger", "validate.sh"), dir], { encoding: "utf-8" });
    assert.equal(result.status, 0, result.stdout + result.stderr);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("the sample shows every feature of the dashboard, so the demo is worth clicking", () => {
  const s = stateOf(committed());
  assert.equal(s.sample, true);
  assert.equal(s.readOnly, true);
  assert.ok(s.decisions.length >= 1, "a decision waiting for a human");
  assert.ok(new Set(s.tasks.map((t) => t.to)).size >= 2, "open work for at least two agents");
  assert.ok(s.done.some((d) => d.review === "pass"), "a reviewed-and-passed task");
  assert.ok(s.done.some((d) => d.review === null && d.kind === "task"), "a finished task nobody reviewed");
  assert.ok(s.checkpoints.some((c) => c.stale === true) && s.checkpoints.some((c) => c.stale === false), "one stale and one current checkpoint");
  const text = s.attention.map((a) => a.text).join("\n");
  assert.match(text, /1 decision waiting/);
  assert.match(text, /^1 defect filed/m, "the same defect is counted once");
  assert.match(text, /has not been reviewed/);
  assert.deepEqual(s.warnings, []);
});

test("the data file is plain data: one default export of JSON and no code", () => {
  const lines = committed().split("\n");
  assert.ok(lines[0].startsWith("// Generated by"), "carries its do-not-edit header");
  assert.ok(lines[2].startsWith("export default {"));
  assert.doesNotThrow(() => stateOf(committed()));
  assert.ok(!/(eval|Function\(|import\(|fetch\()/.test(committed()), "no executable behaviour in a data file");
});

test("the page wires the button to the bundled data and not to the network", () => {
  const html = readFileSync(here("../web/index.html"), "utf-8");
  const app = readFileSync(here("../web/app.js"), "utf-8");
  assert.match(html, /id="try-sample"/);
  assert.match(html, /id="sample-banner"/);
  assert.match(app, /^import sample from "\.\/sample-state\.js"/m);
  const body = app.slice(app.indexOf("function trySample"), app.indexOf("function showDashboard"));
  assert.ok(!/fetch\(|api\(/.test(body), "sample mode must not make a network call");
});
